/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "dark-primary": "#111111",
        "text-primary": "#44566c",
        "dark-focus-border": "#FF6464",
        "dark-mobile-primary": "#1d1d1d",
        "light-bg": "#F8FBFB",
        "light-bg-secondary": "#fcf4ff",
        "light-bg-three": "#fff0f0",
        "light-bg-four": "#edf2f2",
        "light-bg-five": "#F3F6F6",
        "light-bg-six": "EDF2ED",
        "dark-bg": "#0D0D0D",
        "dark-bg-two": "#1c1c1c",
        "dark-bg-three": "#4D4D4D",
        "light-icon": "#F95054",
        "dark-border": "#212425",
        "dark-borde-secondary": "#333333",
        "dark-border-two": "#3D3A3A",
        "main-text": "#A6A6A6",
        "light-text": "#7B7B7B",
        "light-title": "#526377",
        "dark-text": "#b7b7b7",
        "modal-text": "#ef4060",
        "fb-icon": "#1773EA",
        "twitter-icon": "#1C9CEA",
        "dribble-icon": "#e14a84",
        "linkedin-icon": "#0072b1",
        "light-border": "#B5B5B5",
        "light-border-two": "#E3E3E3",
        "focus-border-one": "rgb(81,133,212)",
        "focus-text-one": "#5185D4",
        "focus-border-two": "#CA56F2",
        "btn-primary": "#FA5252",
        "btn-secondary": "#DD2476",
        "btn-test": "rgb(250 82 82 / 0)",
        "icon-color-one": "#E93B81",
        "icon-color-two": "#6AB5B9",
        "icon-color-three": "#FD7590",
        "icon-color-four": "#C17CEB",
        "skill-bg-one": "#fcf4ff",
        "skill-bg-two": "#fefaf0",
        "skill-bg-three": "#fff4f4",
        "skill-bg-four": "#fff0f8",
        "skill-bg-five": "#f3faff",
        "progress-bg-one": "#FF6464",
        "progress-bg-two": "#9272d4",
        "progress-bg-three": "#5185d4",
        "progress-bg-four": "#ca56f2",
        "edu-card-one": "#fff4f4",
        "edu-card-two": "#fff1fb",
        "exp-card-one": "#eef5fa",
        "exp-card-two": "#f2f4ff",
        "gradient-to": "#dd2476",
      },
      backgroundImage: {
        "bg-gradient-to-r":
          "linear-gradient(to right, var(--tw-gradient-stops))",
        "home-bg": "url('/src/images/light-bg.jpg')",
        "close-light": "url('/src/images/close-light.jpg')",
        "home-bg-dark": "url('/src/images/dark-bg.jpg')",
        "close-dark": "url('/src/images/close-dark.png')",
      },
    },
  },
  plugins: [],
  darkMode: "class",
};
